<?php

/**
 * Array with all country codes where this shipping method is shipping
 * @return array country codes with zones
 */
function ibenic_woo_tisak_shipping_countries(){
    return array(
        'BA' => 0,
        'XK' => 0,
        'ME' => 0,
        'RS' => 0,
        'SI' => 0,
        'AT' => 1,
        'BE' => 1,
        'BG' => 1,
        'CZ' => 1,
        'DK' => 1,
        'FR' => 1,
        'DE' => 1,
        'HU' => 1,
        'IT' => 1,
        'NL' => 1,
        'PL' => 1,
        'RO' => 1,
        'SK' => 1,
        'GB' => 1,
        'EE' => 2,
        'FI' => 2,
        'GR' => 2,
        'IE' => 2,
        'LV' => 2,
        'LT' => 2,
        'LU' => 2,
        'PT' => 2,
        'ES' => 2,
        'SE' => 2,
        'AF' => 3,
        'AL' => 3,
        'DZ' => 3,
        'AS' => 3,
        'AD' => 3,
        'AO' => 3,
        'AI' => 3,
        'AG' => 3,
        'AR' => 3,
        'AM' => 3,
        'AW' => 3,
        'AU' => 3,
        'AZ' => 3,
        'BS' => 3,
        'BH' => 3,
        'BD' => 3,
        'BB' => 3,
        'BY' => 3,
        'BZ' => 3,
        'BJ' => 3,
        'BM' => 3,
        'BT' => 3,
        'BO' => 3,
        'BQ' => 3,
        'BW' => 3,
        'BR' => 3,
        'VG' => 3,
        'BN' => 3,
        'BF' => 3,
        'BI' => 3,
        'KH' => 3,
        'CM' => 3,
        'IC' => 3,
        'CV' => 3,
        'KY' => 3,
        'CF' => 3,
        'TD' => 3,
        'CL' => 3,
        'CN' => 3,
        'CO' => 3,
        'KM' => 3,
        'CG' => 3,
        'CD' => 3,
        'CK' => 3,
        'CR' => 3,
        'CI' => 3,
        'CW' => 3,
        'CY' => 3,
        'DJ' => 3,
        'DM' => 3,
        'DO' => 3,
        'TL' => 3,
        'EC' => 3,
        'EG' => 3,
        'SV' => 3,
        'GQ' => 3,
        'ER' => 3,
        'ET' => 3,
        'FO' => 3,
        'FJ' => 3,
        'PF' => 3,
        'GA' => 3,
        'GM' => 3,
        'GE' => 3,
        'GH' => 3,
        'GI' => 3,
        'GL' => 3,
        'GD' => 3,
        'GP' => 3,
        'GU' => 3,
        'GT' => 3,
        'GN' => 3,
        'GW' => 3,
        'GY' => 3,
        'HT' => 3,
        'HN' => 3,
        'HK' => 3,
        'IS' => 3,
        'IN' => 3,
        'ID' => 3,
        'IQ' => 3,
        'IL' => 3,
        'JM' => 3,
        'JP' => 3,
        'JO' => 3,
        'KZ' => 3,
        'KE' => 3,
        'KI' => 3,
        'KR' => 3,
        'FM' => 3,
        'KW' => 3,
        'KG' => 3,
        'LA' => 3,
        'LB' => 3,
        'LS' => 3,
        'LR' => 3,
        'LY' => 3,
        'LI' => 3,
        'MO' => 3,
        'MK' => 3,
        'MG' => 3,
        'MW' => 3,
        'MY' => 3,
        'MV' => 3,
        'ML' => 3,
        'MT' => 3,
        'MH' => 3,
        'MQ' => 3,
        'MR' => 3,
        'MU' => 3,
        'YT' => 3,
        'MX' => 3,
        'MD' => 3,
        'MC' => 3,
        'MN' => 3,
        'MS' => 3,
        'MA' => 3,
        'MZ' => 3,
        'MM' => 3,
        'NA' => 3,
        'NP' => 3,
        'KN' => 3,
        'NC' => 3,
        'NZ' => 3,
        'NI' => 3,
        'NE' => 3,
        'NG' => 3,
        'MP' => 3,
        'NO' => 3,
        'OM' => 3,
        'PK' => 3,
        'PW' => 3,
        'PA' => 3,
        'PG' => 3,
        'PY' => 3,
        'PE' => 3,
        'PH' => 3,
        'PR' => 3,
        'QA' => 3,
        'RE' => 3,
        'RU' => 3,
        'RW' => 3,
        'WS' => 3,
        'SM' => 3,
        'SA' => 3,
        'SN' => 3,
        'SC' => 3,
        'SL' => 3,
        'SG' => 3,
        'SB' => 3,
        'ZA' => 3,
        'LK' => 3,
        'BL' => 3,
        'LC' => 3,
        'SX' => 3,
        'MF' => 3,
        'VC' => 3,
        'SR' => 3,
        'SZ' => 3,
        'CH' => 3,
        'TW' => 3,
        'TJ' => 3,
        'TZ' => 3,
        'TH' => 3,
        'TG' => 3,
        'TO' => 3,
        'TT' => 3,
        'TN' => 3,
        'TR' => 3,
        'TM' => 3,
        'TC' => 3,
        'TV' => 3,
        'UG' => 3,
        'UA' => 3,
        'AE' => 3,
        'UY' => 3,
        'UZ' => 3,
        'VU' => 3,
        'VE' => 3,
        'VN' => 3,
        'VG' => 3,
        'WF' => 3,
        'YE' => 3,
        'ZM' => 3,
        'ZW' => 3,
        );
}

/**
 * Returns the array with prices for a zone
 * @param  number $zone zone number
 * @return array       prices for packages
 */
function ibenic_woo_tisak_get_zone_prices( $zone ) {

    $zonePrice = array(
        0 => array( 
            's' => 95,
            'm' => 105,
            'l' => 135),
        1 => array( 
            's' => 220,
            'm' => 250,
            'l' => 275),
        2 => array( 
            's' => 260,
            'm' => 300,
            'l' => 360),
        3 => array( 
            's' => 470,
            'm' => 550,
            'l' => 790),
        );
    return $zonePrice[ $zone ];
}

/**
 * Returns the prices for the provided country and package
 * @param  string $country ISO country code
 * @param  string $package 
 * @return number          Price for the package and country
 */
function ibenic_woo_tisak_get_price_by_country_and_package( $country, $package ){
    $countries = ibenic_woo_tisak_shipping_countries();

    if( ! isset( $countries[ $country ] ) ) {
        return false;
    }

    $countryZone = (int) $countries[ $country ];

    $packagesFromZone = ibenic_woo_tisak_get_zone_prices( $countryZone );

    $price = $packagesFromZone[ strtolower( $package ) ];

    return $price;
}